baseURL = 'http://example.org/'
languageCode = 'zh-hans'
title = '初链那件小事 - INS 国际讲座系列 #21'
theme = "courses"
canonifyurls = true
disableHugoGeneratorInject = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  type = 'type'